logging.level.org.springframework.ai.chat.client.advisor: DEBUG

spring:
  application:
      name: wtb2.0
  ai:
    ollama:
      chat:
        model: llama3.2
        
traffic:
  apiKey: ${GRAPH_HOPPER_API_KEY}
  apiUrl: https://graphhopper.com
